t_pbl_stat : t_pbl_stat.f90 ../../core/pbl_met.a pbl_met.mod
	gfortran -J../../core -o t_pbl_stat t_pbl_stat.f90 ../../core/pbl_met.a

tStat : tStat.f90 ../pbl_met.a pbl_met.mod
	gfortran -J../../core -o tStat tStat.f90 ../../core/pbl_met.a
